### ISSUE TITLE
Foreign key v bazi

### ISSUE THREAD

**Issue by kulan89** [kulan89/PyJet#4]
Zataknilo se nama je pri tabeli “LET”. Tam imava stolpca “Odhod” in “Prihod”, katera sta oba FK iz tabele “DESTINACIJE” (stolpec “ID”).
Ko želim dodati nov podatek za “Odhod”, mi javi napako “ambiguous column name (Destinacije.ID)”.
Ali torej v eni tabeli ni mozno imeti dveh stolpcev, ki sta oba FK iz enake tabele?

**Comment by jaanos** [comment]
Ko sam poskusim, mi deluje, če poskusim vnesti podatke, npr.
```sql
INSERT INTO Let (ID, Odhod, Prihod, "Tip letala") VALUES (3, 4, 5, 'HondaJet');
```
Deluje mi tako iz SQLiteStudio kot tudi iz Pythona.

Kakorkoli, vsekakor je možno v eni tabeli imeti več FK na isto tabelo. Nisem prepričan, zakaj dobita tako napako - kakšen SQL stavek pa naredita?

Sicer pa svetujem, da v imenih tabel in stolpcev ne uporabljata presledkov, šumnikov in ostalih posebnih znakov (kot npr. `/`, ki v SQL pomeni deljenje). Kot vidita iz zgornjega primera, je treba imena, ki vsebujejo take znake, dati v dvojne navednice - bolje bo torej, da se s tem ne rabita posebej ukvarjati. Glede šumnikov (in ostalih naglašenih/tujih znakov) pa je vedno tako, da ne gre računati, da bodo povsod delovali.

Svetujem vama tudi, da v tabelo `Tip letala` (lahko jo preimenujeta kar v `Tip`, ali pa npr. `TipLetala`) dodasta še številski stolpec `ID`, ki naj bo glavni ključ z lastnostjo `AUTOINCREMENT`. Seveda bo potrebno v tabeli `Let` ustrezno popraviti tuji ključ na ta stolpec. Če želita preprečiti ponavljanje vrednosti, stolpcu `Tip` nastavita še lastnost `UNIQUE`.

**Comment by kulan89** [comment]
Drži ja, z editorjem gre čisto normalno. Napako mi je javljalo, ko sem poskušala vstaviti podatke direktno v tabelo (Data zavihek).
Imena sva popravili, tako da ni več presledkov, šumnikov ipd., bom pa dodala novo verzijo, ko dopolnim še nekaj stvari.

Mimogrede, ali bi bilo vredu, če v tabell "Let" PK "ID" ni nastavljen na "Autoincrement"? Zadevo bi namreč radi naredili tako, da bova imeli tedenske urnike, pri čemer bi radi, da št. oz. ID leta za relacijo LJU - VIE (npr.) ostane enak iz tedna v teden, za povratni let pa se prišteje enica:
LJU - VIE (ID = 200)
VIE - LJU (ID = 201)

In potem, če bi na novo dodali še kakšno destinacijo v Avstriji npr. Salzburg:
LJU - SZG (ID = 202)
SZG - LJU (ID = 203)
(IDdržave za Avstrijo je 2 in tako bi se potem vsi ID letov, ki grejo v enako državo, začeli z enako "stotico").

**Comment by jaanos** [comment]
Načeloma ni nič narobe, če namesto `AUTOINCREMENT` uporabljata svojo shemo za določanje ID-jev, in pri tem projektu najbrž zaradi tega ne bo težav. V praksi bi se sicer lahko hitro zgodilo, da se taka shema podre (npr. če bi imeli več kot 50 letov v isto državo).

V vsakem primeru pa svetujem, da naj vajin spletni vmesnik nič ne ve o tej shemi - če morata npr.  za dani let ugotoviti, v katero državo leti, to naredita z ustreznim `JOIN`om po destinaciji in ne poskušata tega ugotoviti iz ID-ja (to lahko počneta za orientacijo, dokler urejata bazo).

**Comment by kulan89** [comment]
Seveda ja, tako številčenje bova uporabljali samo za svojo orientacijo. Najlepša hvala za vso pomoč!
